### ISSUE TITLE
window 没有getBoundingClientRect 方法

### ISSUE THREAD

**Issue by V-Tom** [ElemeFE/vue-infinite-scroll#1]
[source](https://github.com/ElemeFE/vue-infinite-scroll/blob/master/src/index.js#L159)
如果这里的`element`是`window`,
`getElementTop`就会报错
这里应当加个判断

**Comment by furybean** [comment]
对，是有这个问题，我抽空改下。

**Comment by furybean** [comment]
这个是已经修正的一个问题， npm 上的最新版本是没有问题的。
我忘记 push 到仓库了，刚刚已经 push 到了仓库。

**Comment by mbajur** [comment]
Guys, can you explain what this issue is about in english? I might have some similar issue (Cannot read property 'getBoundingClientRect' of null) but google translator is not able to deal with what youv'e written and i'm not sure if that's the issue i was looking for or should i open a new one.

Thanks :)

**Comment by furybean** [comment]
@mbajur I've fixed this issue on this commit: https://github.com/ElemeFE/vue-infinite-scroll/commit/4955306ca81c39519910becfdf419b292823caa9

What's version do you use? If you use 0.1.2, please open another issue.
